export const products = [
  {
    id: 1,
    title: "Women's Casual Shirt",
    image: ["/pictures/product5.jpg", "/pictures/product2.jpg"],
    productDetails: "women's-casual-shirt",
    price: 495,
    allCategory: "Clothing",
    description:
      "PRETTYGARDEN Women's Babydoll Peplum Shirt Puff Long Sleeve Bow Tie Front Trendy Cute Y2K Going Out Tops",
    color: ["Blue", "White", "Black"],
    size: ["S", "M", "L", "XL"],
    quantity: 1,
  },
  {
    id: 2,
    title: "Gold-Black Pearl Hoop Earrings",
    image: ["/pictures/earnings1.jpg"],
    productDetails: "Gold-Black Pearl Hoop Earrings",
    price: 796,
    allCategory: "Acessories",
    description:
      "In our signature color combination, white + black pearls circle the hoop earrings with gold splashes coming out. For a full set, match it back to the coordinating stretch bracelet.",
    color: ["Gold w Silver"],
    size: ["one S"],
    quantity: 1,
  },
  {
    id: 3,
    title: "Woven Black Slingback Heels",
    image: ["/pictures/Heels1.jpg"],
    productDetails: "Woven Black Slingback Heels",
    price: 79.99,
    allCategory: "Footwear",
    description:
      "Secure day-to-night looks with these on-trend slingback heels. In an easy, long-hours heel height, the pointed-toe shoes have a comfortable strap that make for all-day wear. Pair it back to the matching crossbody bag.",
    color: ["Black"],
    size: ["6", "7", "8", "9"],
    quantity: 1,
  },
  {
    id: 4,
    title: "Glass Pearl Pave Collar Necklace",
    image: ["/pictures/necklace1.jpg"],
    productDetails: "Glass Pearl Pave Collar Necklace",
    price: 89.99,
    allCategory: "Accessories",
    description:
      "High-quality wireless headphones with excellent sound clarityMake a statement when you wear this stunning necklace alone or layered with other chains. This collar design features faux pearl pavé cabochons. In a classic chain link design that's perfect for any outfit, any occasion.",
    color: ["Gold"],
    size: ["One Size"],
    quantity: 1,
  },
  {
    id: 5,
    title: "Woven Crossbody Bag",
    image: ["/pictures/bag.jpg"],
    productDetails: "Woven Crossbody Bag",
    price: 29.99,
    allCategory: "bags",
    description:
      "Perfectly woven for every day, the classic crossbody is the ideal day-to-night bag. Match it back to the coordinating shoes for a full look. ",
    color: ["Black"],
    size: ["One Size"],
    quantity: 1,
  },
  {
    id: 6,
    title: "Oblong Leopard Scarf",
    image: ["/pictures/scraf.jpg"],
    productDetails: "Oblong Leopard Scarf",
    price: 12.99,
    allCategory: "Clothing",
    description:
      "Leopard print can be a daunting addition to any wardrobe, which is why we created this scarf as the perfect entry point into the leopard trend revival. Fashioned with a subtle metallic sheen, the accessory travels well and thanks to the shape, can be worn in a variety of different ways.",
    color: ["Black"],
    size: ["one size"],
    quantity: 1,
  },
];
